### ISSUE TITLE
Time precision with smaller intervals

### ISSUE THREAD

**Issue by Brunni** [coddicat/DebounceThrottle#11]
Hi,

I've read about the precision of DateTime vs StopWatch: The current implementation uses the DateTime.Now to remember the current time. This could probably lead to strange behavior in one of the following cases:
* The system clock is corrected by some time synchronization via internet.
* The precision in the <10ms area might not be good.

At least for the second case, I was not able to get a stable unit test. So I was wondering if there is a certain lower bound for the interval, which should be used.

**Comment by coddicat** [comment]
@Brunni you are right, I will change it to use StopWatch and i will add some tests to archive precision <10ms today-tomorrow

**Comment by coddicat** [comment]
@Brunni published a new 3.0.0 version with the precision < 1ms

also added a new DebounceThreadDispatcher which used Thread instead of Task to archive maximum precision (but not recommended)

**Comment by coddicat** [comment]
@Brunni update me please if you have anything else
