### ISSUE TITLE
Executing on the wrong thread in WPF

### ISSUE THREAD

**Issue by Montago** [coddicat/DebounceThrottle#2]
I used this lib to debounce inputs from the user. 

the action is executed in a different thread than UI - which means that DependencyProperties are inaccessible. 

I had to wrap the inner content of the Action in a different Dispatcher:

debouncer.Debounce(() => 
            {
                Application.Current.Dispatcher.BeginInvoke(new Action(() =>
                {
                    UpdateCarModels();
                }));
            });

**Comment by coddicat** [comment]
I updated the package, plus yes Application.Current.Dispatcher.BeginInvoke you have to do in your case
