### ISSUE TITLE
DebounceAsync shows throttle behavior

### ISSUE THREAD

**Issue by CodingOctocat** [coddicat/DebounceThrottle#3]
I want to save text to file, I need to save in real time, when the typing is finished 1s after the save.

```CS
private readonly DebounceDispatcher _debounceDispatcher = new(1000);

public async Task DumpAsync(string path,string text, IProgress<ProgressInfo>? progress = default, CancellationToken cancellationToken = default)
    {
        if (!CanDump)
        {
            return;
        }

        CanDump = false;

        await _debounceDispatcher.DebounceAsync(async () => {
            progress?.Report(new ProgressInfo(0));

            await File.WriteAllTextAsync(path, text, cancellationToken);

            progress?.Report(new ProgressInfo(1));
        });

        CanDump = true;
    }
```

DebounceAsync shows throttle behavior:
![动画](https://user-images.githubusercontent.com/7220248/187056530-1e3b6e5d-9256-4aeb-bff6-23a72e07f206.gif)

**Comment by coddicat** [comment]
@CodingOctocat  I revised the package, please upgrade to version 2, plus don't AWAIT _debounceDispatcher.DebounceAsync, run it asynchronously

**Comment by CodingOctocat** [comment]
How do I understand this statement? Is not using await contradictory to running asynchronously?
> plus don't AWAIT _debounceDispatcher.DebounceAsync, run it asynchronously

Could you give the code?

**Comment by coddicat** [comment]
@CodingOctocat 
DebounceAsync means the invocation it's a task and this method returns this task, so if you await then it will wait for the execution, so just do not await. here is the working sample code (don't forget to upgrade the NuGet):
```CS
using DebounceThrottle;
string str = "";
var _debounceDispatcher = new DebounceDispatcher(1000);
while (true)
{
    var key = Console.ReadKey(true);
    //trigger when to stop and exit
    if (key.Key == ConsoleKey.Escape) break;
    str += key.KeyChar;
    Console.Write(key.KeyChar);
    Dump("log.txt", str);
}

return;

void Dump(string path, string text, CancellationToken cancellationToken = default)
{
    var task = _debounceDispatcher.DebounceAsync(async () => {
        await File.WriteAllTextAsync(path, text, cancellationToken);
        Console.WriteLine("---- dump ----");
    });
}
```

**Comment by CodingOctocat** [comment]
I always thought the `Async` method was always used in conjunction with `await`, but in that case, why not design it to use the `Debounce()` method?

**Comment by coddicat** [comment]
@CodingOctocat you are right, but here you get the task in case you want run ContinueWith on executing task or explicitly await when it’s invoked
