### ISSUE TITLE
Typo in DelayContidion private method

### ISSUE THREAD

**Issue by Brunni** [coddicat/DebounceThrottle#8]
There is a typo in DelayContidion

**Comment by coddicat** [comment]
@Brunni Hey, thanks for all your comments, I gonna commit these changes today later

**Comment by Brunni** [comment]
@coddicat If you are open to suggestions, I would add some more things, which I found.

**Comment by coddicat** [comment]
@Brunni sure I am interested, thanks for your comments 
new version 2.1.0 has been released 

also I have more an advanced package https://github.com/coddicat/DistributedDebounceThrottle
